name: shutter_ease
description: "A new Flutter project."

# Prevents accidental publishing of the package.
publish_to: "none"

# Defines the version and build number for your application.
# Version format: major.minor.patch+build
version: 1.0.0+1

environment:
  sdk: ^3.5.2

# Dependencies specify other packages needed for the project.
dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons font for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  iconsax: ^0.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  fluttertoast: ^8.2.8
  cloud_firestore: ^5.4.4
  connectivity_plus: ^6.0.5
  lottie: ^3.1.2
  intl: ^0.19.0
  flutter_spinkit: ^5.2.1
  firebase_database: ^11.1.4
  flutter_launcher_icons: ^0.14.1
  http: ^1.2.2
  flutter_localizations:
    sdk: flutter
  shared_preferences:
  smooth_page_indicator: ^1.2.0+3
  show_hide_password: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# Configuration for the launcher icon
flutter_launcher_icons:
  background_color: #FFFFFF,
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/AppLogo.png"
  min_sdk_android: 21

# Linting rules for better coding practices.
flutter_lints: ^4.0.0

flutter:
  # Ensures that Material Icons font is included for use in the app.
  uses-material-design: true

  # Assets to be included in the application.
  assets:
    - assets/images/
    - assets/icons/
    - assets/files/

  # Custom fonts to be used in the application.
  fonts:
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
